name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  tests:
    name: Lint, build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: NPM install, lint and build
        run: |
          npm ci
          npm run lint
          npm run format
          npm run build
      - name: Run tests
        run: |
          npm run test
