name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish on NPM
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: NPM install and build
        run: |
          npm ci
          npm run build
      - name: Check version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3)
          if [[ "v${PACKAGE_VERSION}" != "$TAG_NAME" ]]; then exit 1; fi
      - name: NPM publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          npm publish --access public
